stages:
  #-------------- 
  data_ingestion:
    cmd: python src/ImageClassification/pipeline/stage_01_data_ingestion.py
    deps:
      - src/ImageClassification/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/chicken-fecal-images

  #--------------
  prepare_base_model:
    cmd: python src/ImageClassification/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/ImageClassification/pipeline/stage_02_prepare_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model

  #--------------
  training:
    cmd : python src/ImageClassification/pipeline/stage_03_training.py
    deps:
      - src/ImageClassification/pipeline/stage_03_training.py
      - src/ImageClassification/components/prepare_callbacks.py
      - config/config.yaml
      - artifacts/data_ingestion/chicken-fecal-images
      - artifacts/prepare_base_model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - artifacts/training/model.keras


  #--------------
  evaluation:
    cmd : python src/ImageClassification/pipeline/stage_04_evaluation.py
    deps:
      - src/ImageClassification/pipeline/stage_04_evaluation.py
      - config/config.yaml
      - artifacts/data_ingestion/chicken-fecal-images
      - artifacts/training/model.keras
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
      - scores.json:
          cache: False